### ISSUE TITLE
Speedup the workflow

### ISSUE THREAD

**Issue by Garanas** [FAForever/FAForeverMapEditor#26]
While building the project the container appears to be missing, as shown in the logs with:

```
Unable to find image 'unityci/editor:windows-2022.3.26f1-windows-il2cpp-3' locally
windows-2022.3.26f1-windows-il2cpp-3: Pulling from unityci/editor
```

Various Unity containers can be found in the [Docker hub](https://hub.docker.com/r/unityci/editor). You can [define the container](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer) for a given job.

**Comment by MrRowey** [comment]
currently even caching the docker image that the build process requires the first time takes a long time to cache the docker img and then when its cached the time it is saved is minimal compared to not caching the docker file
