### ISSUE TITLE
Numbers in input field can linger without being assigned

### ISSUE THREAD

**Issue by binarybubble** [FAForever/FAForeverMapEditor#34]
Changes in ther "Areas" tab do not show changes or just dismiss all changes when you clicke another tab or setting.

**Comment by BlackYps** [comment]
The area only gets highlighted when you click on the (arguably very dark) checkbox next to the name. Did you do that?

**Comment by binarybubble** [comment]
You either didn't read or understand the error. you can't change the actual numbers/size of the map.
Any input will just dismiss. It has nothing to do with highlighting the area.

**Comment by BlackYps** [comment]
Suggesting that I didn't read your text is kinda insulting.
But you are right that there was a misunderstanding. I now understand that with "changes" you mean the numbers that define the area borders.

It seems this is a general problem. Apparently text boxes only really assign the new value when you confirm it with enter. When you click in a different field, the new text stays there, but has no effect. Only if you click in the text box again and confirm with enter the value gets assigned. This is not only affecting the Area section. I also found it in the water settings and I assume this is a problem for every text box.

**Comment by binarybubble** [comment]
I apologise for the insult (yes, it was meant as one, I thought you are just a rando who wants to add his 2 cents, caught me on the wrong foot).
yes, It is different in ver 0.78, where the values are saved when leaving the txtbox. 
To my experience so far, AREAS txtboxes are the only ones that behave like this. couldn't reproduce it in water settings or any other in the editor.

**Comment by BlackYps** [comment]
So you insulted the maintainer instead, nice XD

We'll look into the issue. It seems it's not hard to fix.

**Comment by binarybubble** [comment]
Sure, who else?
I thought Jip is the maintainer, I rarely check FAF discord (except pinged directly), altought I have the map editor open usually once per day so I use it quite often.
I've seen you took over now. I can help with QA if you need someone to check things that you updated. english and german speaker.
cheers

**Comment by BlackYps** [comment]
I might come back on that
